version: '3.6'

volumes:
  data: {}
  logs: {}
  config: {}

services:

  srv:
    image: ulm0/gitlab:13.2.6
    container_name: gitlab
    restart: always
    ports:
      - 443:443/tcp
      - 22:22/tcp
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab


